import { IEnemy } from "../../interfaces/enemy";

const enemies = [
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 30hp',
        prefix: 'an',
        baseXp: 100,
        baseHp: 486,
        basePersuasionResistance: 659,

        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 20hp',
        prefix: 'an',
        baseXp: 100,
        baseHp: 539,
        basePersuasionResistance: 693,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 40hp',
        prefix: 'an',
        baseXp: 100,
        baseHp: 730,
        basePersuasionResistance: 613,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 35hp',
        prefix: 'an',
        baseXp: 100,
        baseHp: 792,
        basePersuasionResistance: 503,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 50hp',
        prefix: 'an',
        baseXp: 100,
        baseHp: 293,
        basePersuasionResistance: 608,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 30hp',
        prefix: 'an',
        baseHp: 762,
        basePersuasionResistance: 597,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 20hp',
        prefix: 'an',
        baseHp: 852,
        basePersuasionResistance: 514,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 40hp',
        prefix: 'an',
        baseHp: 884,
        basePersuasionResistance: 419,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 35hp',
        prefix: 'an',
        baseHp: 820,
        basePersuasionResistance: 601,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 50hp',
        prefix: 'an',
        baseHp: 584,
        basePersuasionResistance: 538,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 30hp',
        prefix: 'an',
        baseHp: 926,
        basePersuasionResistance: 552,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 20hp',
        prefix: 'an',
        baseHp: 754,
        basePersuasionResistance: 540,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 40hp',
        prefix: 'an',
        baseHp: 501,
        basePersuasionResistance: 513,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 35hp',
        prefix: 'an',
        baseHp: 682,
        basePersuasionResistance: 345,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 50hp',
        prefix: 'an',
        baseHp: 575,
        basePersuasionResistance: 745,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 30hp',
        prefix: 'an',
        baseHp: 651,
        basePersuasionResistance: 573,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 20hp',
        prefix: 'an',
        baseHp: 790,
        basePersuasionResistance: 483,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 40hp',
        prefix: 'an',
        baseHp: 886,
        basePersuasionResistance: 718,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 35hp',
        prefix: 'an',
        baseHp: 444,
        basePersuasionResistance: 460,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 50hp',
        prefix: 'an',
        baseHp: 939,
        basePersuasionResistance: 382,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 30hp',
        prefix: 'an',
        baseHp: 526,
        basePersuasionResistance: 373,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 20hp',
        prefix: 'an',
        baseHp: 826,
        basePersuasionResistance: 538,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 40hp',
        prefix: 'an',
        baseHp: 838,
        basePersuasionResistance: 351,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 35hp',
        prefix: 'an',
        baseHp: 508,
        basePersuasionResistance: 448,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 50hp',
        prefix: 'an',
        baseHp: 837,
        basePersuasionResistance: 436,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 30hp',
        prefix: 'an',
        baseHp: 649,
        basePersuasionResistance: 776,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 20hp',
        prefix: 'an',
        baseHp: 394,
        basePersuasionResistance: 672,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 40hp',
        prefix: 'an',
        baseHp: 459,
        basePersuasionResistance: 496,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 35hp',
        prefix: 'an',
        baseHp: 571,
        basePersuasionResistance: 732,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 50hp',
        prefix: 'an',
        baseHp: 782,
        basePersuasionResistance: 758,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 30hp',
        prefix: 'an',
        baseHp: 697,
        basePersuasionResistance: 681,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 20hp',
        prefix: 'an',
        baseHp: 949,
        basePersuasionResistance: 541,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 40hp',
        prefix: 'an',
        baseHp: 826,
        basePersuasionResistance: 294,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 35hp',
        prefix: 'an',
        baseHp: 669,
        basePersuasionResistance: 625,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 50hp',
        prefix: 'an',
        baseHp: 753,
        basePersuasionResistance: 379,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 30hp',
        prefix: 'an',
        baseHp: 552,
        basePersuasionResistance: 212,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 20hp',
        prefix: 'an',
        baseHp: 617,
        basePersuasionResistance: 320,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 40hp',
        prefix: 'an',
        baseHp: 666,
        basePersuasionResistance: 663,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 35hp',
        prefix: 'an',
        baseHp: 695,
        basePersuasionResistance: 748,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 50hp',
        prefix: 'an',
        baseHp: 721,
        basePersuasionResistance: 762,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 30hp',
        prefix: 'an',
        baseHp: 840,
        basePersuasionResistance: 518,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 20hp',
        prefix: 'an',
        baseHp: 851,
        basePersuasionResistance: 766,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 40hp',
        prefix: 'an',
        baseHp: 932,
        basePersuasionResistance: 660,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 35hp',
        prefix: 'an',
        baseHp: 401,
        basePersuasionResistance: 623,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 50hp',
        prefix: 'an',
        baseHp: 453,
        basePersuasionResistance: 667,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 30hp',
        prefix: 'an',
        baseHp: 702,
        basePersuasionResistance: 368,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 20hp',
        prefix: 'an',
        baseHp: 687,
        basePersuasionResistance: 505,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 40hp',
        prefix: 'an',
        baseHp: 972,
        basePersuasionResistance: 492,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 35hp',
        prefix: 'an',
        baseHp: 801,
        basePersuasionResistance: 565,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 50hp',
        prefix: 'an',
        baseHp: 713,
        basePersuasionResistance: 328,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 30hp',
        prefix: 'an',
        baseHp: 560,
        basePersuasionResistance: 689,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 20hp',
        prefix: 'an',
        baseHp: 766,
        basePersuasionResistance: 359,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 40hp',
        prefix: 'an',
        baseHp: 822,
        basePersuasionResistance: 553,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 35hp',
        prefix: 'an',
        baseHp: 743,
        basePersuasionResistance: 598,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Abyssal Demon 50hp',
        prefix: 'an',
        baseHp: 637,
        basePersuasionResistance: 578,
        image: 'https://www.maxpixel.net/static/photo/1x/Fire-Demon-Flames-Chaos-Burn-Inflamed-Devil-Hell-2708544.jpg',
        type: 'standard',
        battleDurationMinutes: 1,
    },
    <IEnemy>{
        name: 'Bayhill - Bronze Dragon',
        prefix: 'a',
        baseXp: 100,
        baseHp: 1458,
        basePersuasionResistance: 1170,
        image: 'https://cdn.pixabay.com/photo/2017/01/13/07/57/dragon-1976596_960_720.jpg',
        type: 'mini-boss',
        battleDurationMinutes: 1,
    },
];

export default enemies;